source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftMock_Example', :exclusive => true do
  pod "SwiftMock", :path => "../"
end

target 'SwiftMock_Tests', :exclusive => true do
  pod "SwiftMock", :path => "../"

#  pod 'Quick', '~> 0.3.1'
#  pod 'Nimble'
end
